In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
zero = np.zeros((2,2))
ones = np.ones((2,3))

In [5]:
print(arr1)
print(arr2)
print(zero)
print(ones)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
print (arr1[1],arr1[-1])
print (arr2[1,2])

2 3
6


In [18]:
trig = np.array([0,np.pi/2,np.pi, 1])
print(np.sin(trig))
print(np.cos(trig))
print(np.tan(trig))
arr2 = np.array([4,5,6])
print(np.sqrt(arr2))
print(np.exp(arr2))




[0.00000000e+00 1.00000000e+00 1.22464680e-16 8.41470985e-01]
[ 1.00000000e+00  6.12323400e-17 -1.00000000e+00  5.40302306e-01]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  1.55740772e+00]
[2.         2.23606798 2.44948974]
[ 54.59815003 148.4131591  403.42879349]


In [22]:
val = [("harshini",2007,8.6),("akshaya",2004,9.1),("varshini",2008,8.8)]
dtype1 =[("name",'S10'),("year",int),("gpa",float)]
arr = np.array(val, dtype=dtype1)
print(arr)
print(np.sort(arr,order="name"))
print(np.sort(arr,order="gpa"))




[(b'harshini', 2007, 8.6) (b'akshaya', 2004, 9.1) (b'varshini', 2008, 8.8)]
[(b'akshaya', 2004, 9.1) (b'harshini', 2007, 8.6) (b'varshini', 2008, 8.8)]
[(b'harshini', 2007, 8.6) (b'varshini', 2008, 8.8) (b'akshaya', 2004, 9.1)]
